### PR TITLE
Test 3.1.0

### PR DESCRIPTION
**Pull request by jburba**
I think the test 3.1 notebook is in decent shape, however, the criteria section at the top and the test results are still TBD.  I'm not really sure what the end goal of this notebook was in words.  I know it wasn't to check that the EoR is recovered after in-painting, but maybe more that the in-painting works at some level but what that level is and how we demonstrate success I'm not sure about.  The recovered power spectra after in-painting, with the IDR2.2 parameters at least, don't actually recover the "true" un-flagged power spectra.  One major takeaway from this which I think should go somewhere in this document, though, is that the performance of the in-painting is highly dependent upon the flags and spectral window(s).  Maybe this test isn't so much of a "test," in the traditional sense of power spectrum recovery to within some percentage level, as it is to see and quantify the effects of in-painting inside the H1C analysis pipeline?

### CODE REVIEW

**Comment by jburba** [comment]
I am currently updating the notebook to include the flag retrieval and data subset creation.  I'll push a new commit once I have these sections added. @steven-murray

**Comment by steven-murray** [comment]
In addition to my comments on the notebook itself, we need to discuss what the final conditions for success are. As it stands, I'm inclined to say this fails for now (because of the discrepancy of pspec with FFT), but it seems silly to let such a big discrepancy go so easily. Perhaps we should dig into that a bit more. 

As for conditions of success, I'd say something like the following:

"For in-painting over the full range of LSTs in IDR2.2, performed with the hera_pspec pipeline, in spectral-windows for which no fully-flagged channels exist within the central 50% of the window, and in which flag occupancy of the central 50% is not above X%, the residual of the recovered power to the true power should be within Y%"

**Comment by jburba** [comment]
<p><code>vis_clean</code>  lives inside <code>hera_cal.VisClean.vis_clean</code>  and the <code>hera_cal.Delay_Filter</code>  class is a child class of <code>VisClean</code>.   I can spell that out more clearly in the document if need be.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Expanded the major and minor descriptions, but left the criteria untouched.</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I agree that doing an analysis with parameters that are still being tweaked is tricky.  But, would that mean calling this test failed, at least temporarily?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Added!</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I think I've addressed this one with:</p><p> </p><blockquote>To get a sense of the overall level in the power spectrum of the various simulation components, the following cell produces a plot of the delay power spectra per spw of the individual simulation components _without any flags applied_.&nbsp;The red lines in the lower plots mark the delay power spectrum for the summed dataset and represents the "true" power spectrum that we are trying to recover by in-painting the gaps created by flags in the data.&nbsp;Of particular interest in the plots below are the regions in delay space where the EoR dominates the foreground components.</blockquote>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Visually, there doesn't seem to be too much of a difference, but I think this is where fractional difference plots of the recovered power spectra would come in handy.  We can plot the 10% cuts and different bl orientations on top of one another and see if there's any notable differences.</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I don't know, but I wouldn't think so.  That would suggest that the monopole has been shifted?  Or that the monopole is a cusp of sorts, and that shouldn't be the case either?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>(this is Fig. 17 now that I added a figure in the data creation section)</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Functionizing has been completed, I think.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Took a swing at this, let me know what you think.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Like a git hash for the repository?  Or script specific versioning?</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I've redone the in-painting using values that Nick says are what are currently being used (at least for now).  The new ps waterfalls look much better.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>There's still a shoulder which I think is some sort of flagging sidelobe in the ps waterfalls, but it only goes out to ~ the maximum delay used by the in-painting, so I'm pretty thinking it's an artifact of the GSM CLEAN residuals (these are the dominant CLEAN residuals) os some other CLEAN residual.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>The in-painting v2 ps are still a bit strange, but they're much better than before.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I don't know how valuable this plot is for the test itself, but I think it's interesting.  I think you're right though, that it can't necessarily be trusted.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I think that success statement is reasonable, but I think we also need to place some k-based constraint on that statement, i.e. at k = 0.1 inv Mpc or something like that because the recovery is k dependent.  Thoughts?</p>

**Comment by steven-murray** [comment]
<p>All good, was just wondering if another version had to be printed.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Nice, thanks!</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Hmmm... I'm not seeing it?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Again, I'm not sure I'm seeing this?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I'm not sure I'm seeing this. I think we discussed on a telecon that it might be useful to overlay a grey transparent box over the delays you haven't even tried to clean (or just omit them from the plot), so that we don't get confused looking at it.</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I feel like we should dig into this, but not necessarily in this test. Perhaps one of the comments you can make in the top section for further followup is to check why these curves don't line up.</p><p> </p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Oh yes, definitely need to add a statement about k in there. I'm going to throw some random numbers out there for X and Y: X=10%, Y = 20%. I guess k should be related to the min_delay parameter you set?</p>

**Comment by steven-murray** [comment]
<p>It means (if everything is working as expected) that there is more frequency structure than we would have guessed on large scales. It may also be a smoothing thing?</p><p> </p><p>It doesn't seem to be related to the test being performed here and therefore I don't think we should spend much time on it. However, I'd add it as a bullet point to the top section <code></code>{Brief notes on anything else interesting that was noted during testing} <code></code></p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>This is so much better.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>OK, grey box went the inverse way than I was expecting, but that also works :-). </p><p> </p><p>It's much clearer now, and certainly the results are looking much better. In fact, when using the 10% threshold, the pspec results look <em>better</em> than the DFT ones.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I'll re-iterate this -- it can be a point under the one about the turnover at low non-zero k.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Yup, certainly much better.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>Thanks for functionalising the notebook --- it looks so much better. I think I'm almost ready to approve, mainly waiting on two things:</p><p> </p><ol><li>Make some notes about "odd things that we saw" in that top section (I think I've mentioned two things that can go there). You can also note other summary points there that aren't specifically related to whether it passes/fails, like that outside min_delay things are definitely not useable, and that <code>pspec</code>  routines use different cleaning parameters and we might need to do it again with those exact parameters later. Basically, any summary note you want to make to yourself before you run it again next time :-)</li><li>We need to put the criteria and pass/fail in. Since more people seem to be responsive on slack than Github, do you mind copy/pasting my template up there, filling in X and Y, adding a statement about the k-scale, and asking on Slack whether people agree with the statement? Might be good to also post one or two of the summary plots (from the pspec section?) so that people have a rough idea of what you're talking about. We can then hone the statement more precisely.</li><li>Oh, also, the plots at the bottom with "Relative to EoR" look useful, but I'm not groking what "Relative to EoR" means straight up, and there's no caption. Could you add one?</li></ol>

**Comment by jburba** [comment]
<p>You're not seeing the change?  Or you're not seeing the point addressed in what I wrote?  This is in reference to the written section under Section 3 "H1C_IDR2 and hera-pspec Analysis.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Githash for the H1C_IDR2 repo added to the introduction with the other package hashes.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>Do you think the fractional difference plots are useful?  I was trying to think of the best way to show a couple pieces of information on those plots.  For the internal in-painting (done inside the notebook), the GSM residuals typically keep the recovered power spectra from properly recovering the true power spectrum.  So, I've plotted the fractional difference of the recovered signal and the gsm residuals relative to the true ps i.e. (recovered - true) / true and (gsm CLEAN residuals - true) / true, respectively.  This was just to try and reiterate what's in the delay ps plots above, which is that the deviation of the recovered from the true ps is largely due to the GSM CLEAN residuals.</p><p> </p><p>I was also, in the later plots using the H1C_IDR2 analysis, trying to put a couple of lines on there to show:</p><ol><li>How well we recover the true summed power spectrum (recovered in the legend; (recovered - true) / true)</li><li>How well we recover the EoR power spectrum (eor in the legend; (recovered - eor) / eor)</li></ol><p>In the summed signal, dependent upon the spw, the EoR dominates the foregrounds at sufficiently high delay (&gt;~ 3000 ns, which isn't necessarily of interest to us I don't think for this test).  I put the fractional difference relative to the eor as a first attempt at getting across how well do we recover the EoR.  But, I don't know how useful that additional line is since this test isn't necessarily "do we detect the EoR" and more about "do we reproduce the correct ps."  So, maybe I mislead myself by putting the EoR line in.</p>

**Comment by jburba** [comment]
<p>Is it worth leaving this plot in this notebook?  It doesn't necessarily pertain to the test here, but it's still weird.  If we keep it in, I agree that it should be mentioned in the intro somewhere about weird observed behavior.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by jburba** [comment]
<p>I'm still slightly confused about what you mean by "turnover."  Are you referring to the reflection-like peaks around delays of 200-500 ns?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I'm talking about the first peak at around ~100 ns, only visible in some of the plots. Most have the power flattening towards tau = 0, but some have it turning over.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>That could be useful! Could you maybe make just one of these?</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I think it's all good now. You just hadn't pushed the changes when I looked at it.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>I think it can be left in. The rationale for including it is to explore why results with in-notebook analysis vs pspec are as different as they are. It doesn't need to be gone into detail though.</p>

---

 <a href='https://app.reviewnb.com/HERA-Team/hera-validation/pull/55/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by steven-murray** [comment]
<p>OK. I think it would be safer to take out the EoR lines, since that's not what we're testing and it might be distracting. </p><p> </p><p>Is the motivation for including the fractional plots mostly to show that the dominant source of residuals is from the foregrounds - NOT the EoR? That is, we can start to build confidence that EoR is not surprisingly bad for in-painting? Otherwise I'm not sure what the rationale is: I think it seems obvious that most of the excess power would be from the foregrounds, which have the much larger power. The fractional plots really just seem to be blown-up versions of the delay spectra, but harder to interpret.</p><p> </p><p>They could come in handy for comparing two different baseline orientations, or choices of parameters (eg. the thresholding), where the differences between the two requires a zoom-in to see properly.</p><p> </p>

**Comment by jburba** [comment]
<blockquote>3. Oh, also, the plots at the bottom with "Relative to EoR" look useful, but I'm not groking what "Relative to EoR" means straight up, and there's no caption. Could you add one?</blockquote><p>I tried to address this with a new text section below Figure 10.  Let me know if this clears things up or needs to be explained further.</p>

**Comment by jburba** [comment]
@steven-murray I've updated the 3.1 notebook, hopefully for the last time.  I trimmed a lot of excess and cleaned it up a little bit.  I think it looks pretty good.  You might want to pay special attention to the criteria and summary of results.  I think I worded things okay there, but let me know what you think.  No rush on this, by the way, with the paper in progress and NSF / other applications and such quickly approaching.

**Comment by steven-murray** [comment]
Thanks @jburba. It seems like ReviewNB isn't working for me, so I'll just make some comments here:

- Just after Figure 1, it mentions the "solid black line" which appears to now be grey.
- For the last figure, I think it would be good to mention in the caption what the greyed-out points are (I know you mention it in the text above, but just for clarity)

Otherwise, this looks great!

**Comment by jburba** [comment]
@steven-murray I think I addressed both your comments.  Hopefully this is ready to be merged!

**Review by steven-murray — APPROVED** [review]
Great, thanks so much @jburba. This was a LOT of work, and good work at that.

**Pull request merged**
